---
title: "title should be descriptive, informative, and specific"
author: "Eshta Bhardwaj"
thanks: "Code and data available at:  https://github.com/eshtab/paper_1"
date: "January 30 2023"
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
format: pdf
bibliography: references.bib
---

```{r}
#### Workspace set-up ####

# install.packages("tidyverse")
library(tidyverse)
library(janitor)
```

# Introduction

# Exploratory Review

```{r}

# read in data from inputs folder of R project
raw_trafficdelay_data <-
  read_csv(
    file = "./../../inputs/data/raw_data.csv",
    show_col_types = FALSE,
  )

# Make the names easier to type
trafficdelay_data <-
  clean_names(raw_trafficdelay_data)

# look at unique values for each column
unique(trafficdelay_data$route)
unique(trafficdelay_data$time)
unique(trafficdelay_data$day)
unique(trafficdelay_data$location)
unique(trafficdelay_data$incident)
unique(trafficdelay_data$min_delay)
unique(trafficdelay_data$min_gap)
unique(trafficdelay_data$direction)
unique(trafficdelay_data$vehicle)
```

# Data

```{r}



```

# References
